"""Natural language to SQL agent with read-only safety checks."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Any

import pandas as pd

from src.ai.business_analyst_agent import (
    AIConfigurationError,
    AIResponseError,
    ClaudeMessageClient,
    _build_anthropic_client,
    _extract_text,
    _model_candidates,
    _provider_error_message,
    create_message_with_model_fallback,
)


FORBIDDEN_SQL_KEYWORDS = {
    "alter",
    "attach",
    "create",
    "delete",
    "detach",
    "drop",
    "insert",
    "pragma",
    "replace",
    "truncate",
    "update",
    "vacuum",
}


class SQLSafetyError(ValueError):
    """Raised when generated SQL is unsafe or out of scope."""


@dataclass(frozen=True)
class TextToSQLResponse:
    """Structured response generated by the SQL agent."""

    sql: str
    explanation: str
    chart_recommendation: str
    raw_response: str


class NaturalLanguageSQLAgent:
    """Generate safe SQLite SELECT queries from business questions."""

    def __init__(self, api_key: str, model: str, client: ClaudeMessageClient | None = None, provider: str = "claude") -> None:
        if not api_key and client is None:
            raise AIConfigurationError("An AI API key is required to use the Natural Language SQL Agent.")

        self.provider = provider
        self.models = _model_candidates(model, provider=provider)
        if provider == "gemini":
            from src.ai.business_analyst_agent import _build_gemini_client

            self._client = client or _build_gemini_client(api_key=api_key, model=model)
        else:
            self._client = client or _build_anthropic_client(api_key)

    def generate_sql(
        self,
        question: str,
        table_name: str,
        column_metadata: pd.DataFrame,
        row_limit: int = 100,
    ) -> TextToSQLResponse:
        """Generate and validate a read-only SQL query for one saved table."""
        clean_question = question.strip()
        if not clean_question:
            raise ValueError("SQL question cannot be empty.")

        prompt = _build_sql_prompt(clean_question, table_name, column_metadata, row_limit)
        response = create_message_with_model_fallback(
            client=self._client,
            models=self.models,
            provider=self.provider,
            max_tokens=900,
            temperature=0,
            system=(
                "You are a careful SQLite analyst. Generate only read-only SELECT SQL. "
                "Use only the provided table and columns. Return valid JSON only."
            ),
            messages=[{"role": "user", "content": prompt}],
        )
        raw_text = _extract_text(response)
        parsed = _parse_sql_response(raw_text)
        safe_sql = validate_select_sql(parsed.sql, allowed_table=table_name, row_limit=row_limit)
        return TextToSQLResponse(
            sql=safe_sql,
            explanation=parsed.explanation,
            chart_recommendation=parsed.chart_recommendation,
            raw_response=raw_text,
        )


def validate_select_sql(sql: str, allowed_table: str, row_limit: int = 100) -> str:
    """Validate that SQL is a single read-only SELECT against the allowed table."""
    cleaned = sql.strip().rstrip(";").strip()
    if not cleaned:
        raise SQLSafetyError("Generated SQL is empty.")
    if ";" in cleaned:
        raise SQLSafetyError("Only one SQL statement is allowed.")
    if not re.match(r"^select\b", cleaned, flags=re.IGNORECASE):
        raise SQLSafetyError("Only SELECT queries are allowed.")

    tokens = {token.casefold() for token in re.findall(r"\b[a-zA-Z_][a-zA-Z0-9_]*\b", cleaned)}
    blocked = tokens.intersection(FORBIDDEN_SQL_KEYWORDS)
    if blocked:
        raise SQLSafetyError(f"Unsafe SQL keyword detected: {sorted(blocked)[0].upper()}.")

    referenced_tables = _extract_referenced_tables(cleaned)
    if referenced_tables != {allowed_table.casefold()}:
        raise SQLSafetyError("Generated SQL must query only the selected saved table.")

    if not re.search(r"\blimit\b", cleaned, flags=re.IGNORECASE):
        cleaned = f"{cleaned} LIMIT {row_limit}"
    return cleaned


def _build_sql_prompt(question: str, table_name: str, column_metadata: pd.DataFrame, row_limit: int) -> str:
    columns = column_metadata.to_dict(orient="records")
    payload = {
        "question": question,
        "table_name": table_name,
        "columns": columns,
        "rules": [
            "Use SQLite syntax.",
            "Query only the provided table_name.",
            "Return one SELECT statement only.",
            f"Use LIMIT {row_limit} unless aggregation returns one row.",
            "Do not modify data or schema.",
        ],
    }
    return (
        "Convert the business question into SQL. Return JSON with exactly these keys: "
        "sql, explanation, chart_recommendation.\n\n"
        f"Context:\n{json.dumps(payload, default=str, indent=2)}"
    )


def _parse_sql_response(raw_text: str) -> TextToSQLResponse:
    try:
        payload: dict[str, Any] = json.loads(raw_text)
    except json.JSONDecodeError as exc:
        raise AIResponseError("AI SQL response was not valid JSON.") from exc

    sql = str(payload.get("sql", "")).strip()
    explanation = str(payload.get("explanation", "")).strip()
    chart_recommendation = str(payload.get("chart_recommendation", "")).strip()
    if not sql or not explanation or not chart_recommendation:
        raise AIResponseError("AI SQL response did not include sql, explanation, and chart_recommendation.")
    return TextToSQLResponse(sql=sql, explanation=explanation, chart_recommendation=chart_recommendation, raw_response=raw_text)


def _extract_referenced_tables(sql: str) -> set[str]:
    table_matches = re.findall(r"\b(?:from|join)\s+([\"`\[]?[a-zA-Z_][a-zA-Z0-9_]*[\"`\]]?)", sql, flags=re.IGNORECASE)
    return {match.strip('"`[]').casefold() for match in table_matches}